import type { HistoryEntry, Medicine, PatientProfile, AppSettings } from './types';

export const todayMedicines: Medicine[] = [
  {
    id: 'med-001',
    name: 'Paracetamol',
    dosage: '500mg',
    form: 'Tablet',
    scheduledTime: '08:00',
    status: 'taken',
    verification: 'verified',
    notes: 'Take with breakfast',
    color: 'primary',
  },
  {
    id: 'med-002',
    name: 'Metformin',
    dosage: '850mg',
    form: 'Tablet',
    scheduledTime: '09:00',
    status: 'taken',
    verification: 'verified',
    notes: 'After meals',
    color: 'success',
  },
  {
    id: 'med-003',
    name: 'Atorvastatin',
    dosage: '20mg',
    form: 'Tablet',
    scheduledTime: '13:00',
    status: 'pending',
    verification: 'pending',
    notes: 'After lunch',
    color: 'warning',
  },
  {
    id: 'med-004',
    name: 'Vitamin D3',
    dosage: '1000 IU',
    form: 'Capsule',
    scheduledTime: '15:30',
    status: 'pending',
    verification: 'pending',
    notes: 'With water',
    color: 'primary',
  },
  {
    id: 'med-005',
    name: 'Omeprazole',
    dosage: '20mg',
    form: 'Capsule',
    scheduledTime: '18:00',
    status: 'pending',
    verification: 'pending',
    notes: 'Before dinner',
    color: 'warning',
  },
  {
    id: 'med-006',
    name: 'Aspirin',
    dosage: '75mg',
    form: 'Tablet',
    scheduledTime: '21:00',
    status: 'pending',
    verification: 'pending',
    notes: 'Before bed',
    color: 'danger',
  },
];

export const historyEntries: HistoryEntry[] = [
  {
    id: 'h-001',
    date: '2026-06-27',
    medicine: 'Paracetamol',
    dosage: '500mg',
    scheduledTime: '08:00',
    verificationTime: '08:04',
    status: 'verified',
    remarks: 'Medicine verified. Safe to take.',
    confidence: 98.6,
    detectedName: 'Paracetamol',
    expiryDate: '2027-04-30',
  },
  {
    id: 'h-002',
    date: '2026-06-27',
    medicine: 'Metformin',
    dosage: '850mg',
    scheduledTime: '09:00',
    verificationTime: '09:02',
    status: 'verified',
    remarks: 'Medicine verified. Safe to take.',
    confidence: 97.2,
    detectedName: 'Metformin',
    expiryDate: '2026-11-15',
  },
  {
    id: 'h-003',
    date: '2026-06-26',
    medicine: 'Atorvastatin',
    dosage: '20mg',
    scheduledTime: '13:00',
    verificationTime: '13:11',
    status: 'wrong',
    remarks: 'Wrong medicine detected. Reminder continued.',
    confidence: 91.4,
    detectedName: 'Rosuvastatin',
    expiryDate: '2027-02-20',
  },
  {
    id: 'h-004',
    date: '2026-06-26',
    medicine: 'Vitamin D3',
    dosage: '1000 IU',
    scheduledTime: '15:30',
    verificationTime: '15:34',
    status: 'verified',
    remarks: 'Medicine verified. Safe to take.',
    confidence: 99.1,
    detectedName: 'Vitamin D3',
    expiryDate: '2028-01-10',
  },
  {
    id: 'h-005',
    date: '2026-06-26',
    medicine: 'Omeprazole',
    dosage: '20mg',
    scheduledTime: '18:00',
    verificationTime: '18:09',
    status: 'expired',
    remarks: 'Expired medicine. Do not consume.',
    confidence: 94.8,
    detectedName: 'Omeprazole',
    expiryDate: '2025-12-01',
  },
  {
    id: 'h-006',
    date: '2026-06-25',
    medicine: 'Aspirin',
    dosage: '75mg',
    scheduledTime: '21:00',
    verificationTime: '21:06',
    status: 'verified',
    remarks: 'Medicine verified. Safe to take.',
    confidence: 96.7,
    detectedName: 'Aspirin',
    expiryDate: '2027-08-22',
  },
  {
    id: 'h-007',
    date: '2026-06-25',
    medicine: 'Paracetamol',
    dosage: '500mg',
    scheduledTime: '08:00',
    verificationTime: '08:03',
    status: 'verified',
    remarks: 'Medicine verified. Safe to take.',
    confidence: 98.2,
    detectedName: 'Paracetamol',
    expiryDate: '2027-04-30',
  },
  {
    id: 'h-008',
    date: '2026-06-25',
    medicine: 'Metformin',
    dosage: '850mg',
    scheduledTime: '09:00',
    verificationTime: '—',
    status: 'skipped',
    remarks: 'Patient skipped reminder.',
    confidence: undefined,
    detectedName: undefined,
    expiryDate: undefined,
  },
  {
    id: 'h-009',
    date: '2026-06-24',
    medicine: 'Atorvastatin',
    dosage: '20mg',
    scheduledTime: '13:00',
    verificationTime: '13:05',
    status: 'verified',
    remarks: 'Medicine verified. Safe to take.',
    confidence: 95.9,
    detectedName: 'Atorvastatin',
    expiryDate: '2027-02-20',
  },
  {
    id: 'h-010',
    date: '2026-06-24',
    medicine: 'Omeprazole',
    dosage: '20mg',
    scheduledTime: '18:00',
    verificationTime: '18:02',
    status: 'verified',
    remarks: 'Medicine verified. Safe to take.',
    confidence: 97.4,
    detectedName: 'Omeprazole',
    expiryDate: '2026-10-18',
  },
  {
    id: 'h-011',
    date: '2026-06-23',
    medicine: 'Vitamin D3',
    dosage: '1000 IU',
    scheduledTime: '15:30',
    verificationTime: '15:33',
    status: 'verified',
    remarks: 'Medicine verified. Safe to take.',
    confidence: 98.8,
    detectedName: 'Vitamin D3',
    expiryDate: '2028-01-10',
  },
  {
    id: 'h-012',
    date: '2026-06-23',
    medicine: 'Aspirin',
    dosage: '75mg',
    scheduledTime: '21:00',
    verificationTime: '21:08',
    status: 'wrong',
    remarks: 'Wrong medicine detected. Reminder continued.',
    confidence: 89.7,
    detectedName: 'Clopidogrel',
    expiryDate: '2027-06-30',
  },
];

export const defaultProfile: PatientProfile = {
  name: 'Eleanor Whitfield',
  age: 72,
  gender: 'Female',
  bloodGroup: 'O+',
  weight: '62 kg',
  height: '5\'4"',
  medicalConditions: ['Type 2 Diabetes', 'Hypertension', 'Mild Arthritis'],
  allergies: ['Penicillin', 'Sulfa drugs'],
  emergencyContact: {
    name: 'Marcus Whitfield',
    relationship: 'Son',
    phone: '+1 (415) 555-0142',
  },
  doctor: {
    name: 'Dr. Anika Ramanathan',
    specialty: 'Geriatric Physician',
    phone: '+1 (415) 555-0199',
    hospital: 'Bayview Medical Center',
  },
  currentMedicines: [
    'Paracetamol 500mg',
    'Metformin 850mg',
    'Atorvastatin 20mg',
    'Vitamin D3 1000 IU',
    'Omeprazole 20mg',
    'Aspirin 75mg',
  ],
};

export const defaultSettings: AppSettings = {
  reminderInterval: 10,
  voiceLanguage: 'en-US',
  alarmVolume: 70,
  darkMode: false,
  emergencyContact: '+1 (415) 555-0142',
  notifications: {
    push: true,
    email: true,
    sms: false,
    voice: true,
  },
};

export const quickStats = {
  takenToday: 2,
  remainingToday: 4,
  missedThisWeek: 1,
  verificationSuccessRate: 92.4,
  weeklyCompliance: 88,
  totalScans: 142,
};
